<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ghost" name="chapter07.validated.CoordinateTest" tests="9" failures="1" timestamp="3 Mar 2015 05:14:21 GMT" time="1.475" errors="0">
  <testcase name="testVaildCoordinate" time="0.003" classname="chapter07.validated.CoordinateTest"/>
  <testcase name="testInvalidCoordinate" time="1.323" classname="chapter07.validated.CoordinateTest">
    <failure type="org.testng.TestException" message="
Expected exception org.hibernate.exception.ConstraintViolationException but got org.testng.TestException: 
Expected exception org.hibernate.exception.ConstraintViolationException but got javax.validation.ConstraintViolationException: Validation failed for classes [au.com.aussie.chapter07.validated.Coordinate] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage=&#039;Failed quadrant III test&#039;, propertyPath=, rootBeanClass=class au.com.aussie.chapter07.validated.Coordinate, messageTemplate=&#039;Failed quadrant III test&#039;}
]">
      <![CDATA[org.testng.TestException: 
Expected exception org.hibernate.exception.ConstraintViolationException but got org.testng.TestException: 
Expected exception org.hibernate.exception.ConstraintViolationException but got javax.validation.ConstraintViolationException: Validation failed for classes [au.com.aussie.chapter07.validated.Coordinate] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='Failed quadrant III test', propertyPath=, rootBeanClass=class au.com.aussie.chapter07.validated.Coordinate, messageTemplate='Failed quadrant III test'}
]
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception org.hibernate.exception.ConstraintViolationException but got javax.validation.ConstraintViolationException: Validation failed for classes [au.com.aussie.chapter07.validated.Coordinate] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='Failed quadrant III test', propertyPath=, rootBeanClass=class au.com.aussie.chapter07.validated.Coordinate, messageTemplate='Failed quadrant III test'}
]
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 16 more
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [au.com.aussie.chapter07.validated.Coordinate] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='Failed quadrant III test', propertyPath=, rootBeanClass=class au.com.aussie.chapter07.validated.Coordinate, messageTemplate='Failed quadrant III test'}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:159)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:94)
	at org.hibernate.action.internal.EntityIdentityInsertAction.preInsert(EntityIdentityInsertAction.java:178)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:75)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:229)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:209)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:193)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:321)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:208)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:151)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:78)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:772)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:746)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:750)
	at chapter07.validated.CoordinateTest.persist(CoordinateTest.java:31)
	at chapter07.validated.CoordinateTest.testVaildCoordinate(CoordinateTest.java:19)
	at chapter07.validated.CoordinateTest.testInvalidCoordinate(CoordinateTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 18 more
]]>
    </failure>
  </testcase> <!-- testInvalidCoordinate -->
  <testcase name="testVaildCoordinate" time="0.004" classname="chapter07.validated.CoordinateTest"/>
  <testcase name="testVaildCoordinate" time="0.123" classname="chapter07.validated.CoordinateTest"/>
  <testcase name="testVaildCoordinate" time="0.004" classname="chapter07.validated.CoordinateTest"/>
  <testcase name="testVaildCoordinate" time="0.004" classname="chapter07.validated.CoordinateTest"/>
  <testcase name="testVaildCoordinate" time="0.007" classname="chapter07.validated.CoordinateTest"/>
  <testcase name="testVaildCoordinate" time="0.004" classname="chapter07.validated.CoordinateTest"/>
  <testcase name="testVaildCoordinate" time="0.003" classname="chapter07.validated.CoordinateTest"/>
</testsuite> <!-- chapter07.validated.CoordinateTest -->
